name: Build MI8SE(sirius) MIUI Kernel

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y autoconf bc bison build-essential ccache cpio curl flex gawk gcc g++-multilib gcc-multilib git gnupg gperf libc6 libstdc++6 lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils libncurses-dev libiberty-dev lzop kmod imagemagick pngcrush wget zip zlib1g-dev unzip rsync schedtool squashfs-tools xsltproc openjdk-8-jdk language-pack-zh-hans p7zip-full p7zip-rar python vim
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone --depth=1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git -b sirius-q-oss --recurse-submodules android_kernel_xiaomi_sdm710
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ndk-release-r21 --no-tags ~/aarch64-linux-android-4.9
          git clone https://github.com/SakuraNotStupid/AnyKernel3
      - name: Compiling Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=/home/runner/aarch64-linux-android-4.9/bin/aarch64-linux-android-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710
          make O="$output_dir" \
                      sirius_user_defconfig
          make -j $(nproc) \
                       O="$output_dir"
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 8 SE
          Code: Sirius/Xmsirius
          Build Code: ${{ github.run_number }}
          Only For LineageOS 20(Official)
          KernelSU For MI8SE" >> INFO.txt
          
      - name: Packaging the Kernel
        run: |
          cp -v android_kernel_xiaomi_sdm710/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MI8SE-KernelSU_LineageOS20.zip *
          popd
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MI8SE-KernelSU_LineageOS20.zip
          name: " MI8SE-KernelSU_LineageOS20"
          tag: " ${{ github.run_number }}_MI8SE-KernelSU_LineageOS20"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
