name: Build MI8SE(sirius) 2

on:
  workflow_dispatch:

jobs:
  KSUForSirius:
    runs-on: ubuntu-18.04
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/cduang/android_kernel_xiaomi_sdm710-2 -b lineage-18.1 --depth=1 --recurse-submodules android_kernel_xiaomi_sdm710
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ndk-release-r21 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9  -b ndk-release-r21 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/cduang/AnyKernel3
          mkdir clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android10-qpr1-release/clang-r353983c.tar.gz -q --show-progress
          tar -C "clang" -xvzf clang-r353983c.tar.gz
          git clone https://github.com/cduang/KernelSU
          mkdir android_kernel_xiaomi_sdm710/drivers/kernelsu && cp -rv KernelSU/kernel/* android_kernel_xiaomi_sdm710/drivers/kernelsu
          echo "obj-y += kernelsu/" >> android_kernel_xiaomi_sdm710/drivers/Makefile
          echo "CONFIG_KPROBES=y" >> android_kernel_xiaomi_sdm710/arch/arm64/configs/sirius_defconfig
          echo "CONFIG_HAVE_KPROBES=y" >> android_kernel_xiaomi_sdm710/arch/arm64/configs/sirius_defconfig
          echo "CONFIG_KPROBE_EVENTS=y" >> android_kernel_xiaomi_sdm710/arch/arm64/configs/sirius_defconfig
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710
          make O="$output_dir" \
                  sirius_user_defconfig
          make -j$(nproc) \
                  O="$output_dir" \
                  CC=clang 2>&1 |tee kernel.log
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 8 SE
          Code: Sirius/Xmsirius
          Build Code: ${{ github.run_number }}
          Only For MIUI
          KernelSU For MI8SE" >> INFO.txt
          
      - name: Packaging the Kernel
        run: |
          cp -v android_kernel_xiaomi_sdm710/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MI8SE-MIUI.zip *
          popd
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MI8SE-MIUI.zip
          name: " MI8SE-MIUI"
          tag: " ${{ github.run_number }}_MI8SE-MIUI"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
