name: Build Ollvm

on:
  workflow_dispatch:

jobs:
  Ollvm_For_Me:
    runs-on: ubuntu-18.04
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y  zip git wget p7zip-full repo bison
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone -b llvm-9.0.1 https://github.com/cduang/obfuscator.git  --depth=1  obfuscator
          cd obfuscator
          pwd
      - name: Modifying Config
        run: |    
                  #echo "source \"drivers/kernelsu/Kconfig\"" >> android_kernel_xiaomi_sdm710/drivers/Kconfig
      - name: Compiling Ollvm
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../obfuscator/
          make -j7
          pwd
          ls     
      - name: Creating Config Info
        run: |
          echo "Device: My Linux
          Code: Linux/C
          Build Code: ${{ github.run_number }}
          Only For Me
          Ollvm For Me" >> INFO.txt
          
      - name: Packaging the Ollvm
        run: |
          mkdir Ollvm
          cp -rv bin  Ollvm
          pushd Ollvm
                7z a -mx9 ../Ollvm.zip *
          popd
      - name: Uploading Ollvm Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Ollvm.zip
          name: " Ollvm"
          tag: " ${{ github.run_number }}_Ollvm"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
