name: Build Ollvm

on:
  workflow_dispatch:

jobs:
  Ollvm_For_Me:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y  zip git wget p7zip-full repo bison
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          #git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ndk-release-r21 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9  
          #git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9  -b ndk-release-r21 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          #git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 11.0 ~/clang

          git clone -b r23c-release https://github.com/codetronik/ollvm-ndk.git
          cd ollvm-ndk
          pwd
      - name: Modifying Config
        run: |    
                  #echo "source \"drivers/kernelsu/Kconfig\"" >> android_kernel_xiaomi_sdm710/drivers/Kconfig
      - name: Compiling Ollvm
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          cp manifest_8481493.xml .repo/manifests
          repo init -m manifest_8481493.xml
          repo sync -c
          curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
          sudo dpkg -i libffi6_3.2.1-8_amd64.deb
          python toolchain/llvm_android/build.py
                  #python toolchain/llvm_android/build.py --no-build=linux // windows binary
          pwd
          ls     
      - name: Creating Config Info
        run: |
          echo "Device: My Linux
          Code: Linux/C
          Build Code: ${{ github.run_number }}
          Only For Me
          Ollvm For Me" >> INFO.txt
          
      - name: Packaging the Ollvm
        run: |
          mkdir Ollvm
          cp -rv ollvm-ndk/out/  Ollvm
          pushd Ollvm
                7z a -mx9 ../Ollvm.zip *
          popd
      - name: Uploading Ollvm Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Ollvm.zip
          name: " Ollvm"
          tag: " ${{ github.run_number }}_Ollvm"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
